version: "3.9"

services:
  light-emitting-desk:
    image: pikesley/light-emitting-desk
    volumes:
      - .:/opt/light-emitting-desk
      - /Users/sam/.ssh:/root/.ssh
    ports:
      - 5000:5000
      - 8888:8888
      - 8000:80
    command: tail -f /dev/null

  light-emitting-desk-server:
    image: pikesley/light-emitting-desk
    volumes:
      - .:/opt/light-emitting-desk
    ports:
      - 5050:5050
    command: bash -c "make redis && gunicorn -b 0.0.0.0:5050 webserver:app"

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
